### ISSUE TITLE
error with lform ?

### ISSUE THREAD

**Issue by Rosnyni** [LHNCBC/formbuilder-lhcforms#85] opened 2024-06-10 12:40 UTC
There is a trouble with the formBuilder : 

![image](https://github.com/LHNCBC/formbuilder-lhcforms/assets/61731606/ba312f46-a212-43c0-818f-3190defdf7b0)

It seems to be linked to the last lform library deployement. 

Sincerely

Nicolas

**Comment by plynchnlm** [comment] 2024-06-10 19:10
Correct.  Something went wrong with the last lforms deployment, and it is now fixed.  We are looking into why it did not fall back to the previous version as intended.  Sorry for the inconvenience, and thanks for bringing it to our attention.

**Closed by plynchnlm** 2024-06-10 19:10 UTC
